Refactor, delete person references
AY2324S1-CS2103T-T12-3/tp pull request #131
Opened 2023-11-01 10:27 UTC by jellywaiyan

Could not resolve error in: LogicmManagerTest lines 63 onwards

2023-11-02 10:46 UTC, Badatprogrammiing commented on src/main/java/seedu/address/logic/parser/AddressBookParser.java
> -        case FindCommand.COMMAND_WORD:
is this supposed to be deleted?

2023-11-02 10:48 UTC, Badatprogrammiing commented on src/main/java/seedu/address/logic/parser/person/ParserUtil.java
> -
This entire file can de deleted right?

2023-11-02 10:52 UTC, Badatprogrammiing commented on src/main/java/seedu/address/model/AddressBook.java
> +        return assignments.equals(otherAddressBook.assignments);
Can u add internshipRoles.equals... and internshipTask.equals as well?

2023-11-02 10:52 UTC, Badatprogrammiing commented on src/main/java/seedu/address/model/AddressBook.java
> -    }
I dont think this toString method shld be removed, just update it with the current lists

2023-11-02 10:53 UTC, Badatprogrammiing commented on src/main/java/seedu/address/model/AddressBook.java
> -    }
same for this as wll, update with the current list

2023-11-02 11:03 UTC, Badatprogrammiing commented on src/test/java/seedu/address/model/unique/UniqueListTest.java
>          List<UniqueMock> listWithDuplicateUniqueMocks = Arrays.asList(u1, u1);
This entire file, should not have test cases being deleted. I forgot to name to change all references to person

2023-11-02 11:14 UTC, Badatprogrammiing requested changes
as per the above comments

2023-11-02 17:44 UTC, seewhyjay approved these changes
sendit

2023-11-03 04:00 UTC, Badatprogrammiing approved these changes

2023-11-06 02:25 UTC, merged